In [20]:
import numpy as np

# Create a 3x3x3 array with random values between 0 and 1
random_array = np.random.rand(3, 3, 3)

print(random_array)



[[[0.49315779 0.75732705 0.24249966]
  [0.81960022 0.27580535 0.07975614]
  [0.79783397 0.52541031 0.74249198]]

 [[0.18794023 0.82765347 0.29439243]
  [0.83182244 0.67993008 0.86908389]
  [0.81696325 0.36500086 0.58961963]]

 [[0.71046648 0.86876122 0.17156226]
  [0.10820674 0.83900818 0.7225705 ]
  [0.484075   0.13821406 0.48187266]]]


In [21]:
import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Fill the values just below the diagonal
for i in range(1, 5):
    matrix[i, i - 1] = i

print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [22]:
import numpy as np

# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8), dtype=int)

# Fill the checkerboard pattern
matrix[1::2, ::2] = 1  # Odd rows, even columns
matrix[::2, 1::2] = 1  # Even rows, odd columns

print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [23]:
import numpy as np

# Create a random 5x5 matrix
random_matrix = np.random.rand(5, 5)

# Calculate the mean and standard deviation
mean = random_matrix.mean()
std_dev = random_matrix.std()

# Normalize the matrix
normalized_matrix = (random_matrix - mean) / std_dev

print("Random Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Random Matrix:
[[0.2160315  0.28733344 0.77055623 0.64296936 0.40989756]
 [0.67072767 0.12413484 0.80846173 0.0316376  0.02827281]
 [0.8335525  0.13679053 0.0084725  0.61478796 0.97382319]
 [0.99290174 0.09713957 0.42276483 0.04616908 0.56152321]
 [0.15250052 0.05976386 0.10527316 0.92111985 0.50704178]]

Normalized Matrix:
[[-0.60535886 -0.39052475  1.06543473  0.68101305 -0.02123672]
 [ 0.76464937 -0.88224526  1.17964473 -1.16094122 -1.1710794 ]
 [ 1.2552437  -0.84411341 -1.23073809  0.59610195  1.67788198]
 [ 1.73536601 -0.96358253  0.0175326  -1.11715758  0.43561425]
 [-0.79677891 -1.07619624 -0.93907585  1.51908579  0.27146067]]


In [24]:
# Define two lists
list1 = [1, 2, 3, 4, 5]
list2 = [3, 4, 5, 6, 7]

# Use set intersection to find common values
common_values = list(set(list1) & set(list2))

print(common_values)


import numpy as np

# Define two NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Use np.intersect1d() to find common values
common_values = np.intersect1d(array1, array2)

print(common_values)


[3, 4, 5]
[3 4 5]


In [25]:
from datetime import datetime, timedelta

# Get today's date
today = datetime.now().date()

# Calculate yesterday and tomorrow
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)


today_str = today.strftime("%Y-%m-%d")
yesterday_str = yesterday.strftime("%Y-%m-%d")
tomorrow_str = tomorrow.strftime("%Y-%m-%d")

# Print the dates
print("Yesterday:", yesterday_str)
print("Today:", today_str)
print("Tomorrow:", tomorrow_str)


Yesterday: 2023-09-22
Today: 2023-09-23
Tomorrow: 2023-09-24


In [26]:
import numpy as np

# Generate two random arrays A and B
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

# Check if A and B are equal
are_equal = np.array_equal(A, B)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


Arrays A and B are not equal.


In [27]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random vector with the maximum value replaced by 0:")
print(random_vector)


Random vector with the maximum value replaced by 0:
[0.10197913 0.42142177 0.915039   0.24297851 0.69769714 0.33928398
 0.83358104 0.0628842  0.         0.34849884]


In [28]:
# Define a Python list
my_list = [1, 2, 3, 4, 5]

# Use a for loop to print each element
for element in my_list:
    print(element)


import numpy as np

# Define a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Use a for loop to print each element
for element in my_array:
    print(element)


1
2
3
4
5
1
2
3
4
5


In [29]:
import numpy as np


matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1)

# Subtract the row means from the matrix
normalized_matrix = matrix - row_means[:, np.newaxis]

print("Original Matrix:")
print(matrix)

print("\nMatrix with Row Means Subtracted:")
print(normalized_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix with Row Means Subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [30]:
import numpy as np

# Define the original vector
original_vector = np.array([1, 2, 3, 4, 5])

# Define the indices where you want to add 1
indices_to_add_1 = np.array([1, 3, 4])

# Create a new vector with 1 added to specified indices
modified_vector = original_vector.copy()  # Create a copy to avoid modifying the original vector
modified_vector[indices_to_add_1] += 1

print("Original Vector:")
print(original_vector)

print("\nModified Vector:")
print(modified_vector)


Original Vector:
[1 2 3 4 5]

Modified Vector:
[1 3 3 5 6]


In [31]:
import numpy as np

# Create two  matrices
matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_B = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])

# Calculate the dot product of the two matrices
dot_product_result = np.dot(matrix_A, matrix_B)

# Extract the diagonal elements of the dot product matrix
diagonal_elements = np.diag(dot_product_result)

print("Matrix A:")
print(matrix_A)

print("\nMatrix B:")
print(matrix_B)

print("\nDot Product:")
print(dot_product_result)

print("\nDiagonal of the Dot Product:")
print(diagonal_elements)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Dot Product:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Diagonal of the Dot Product:
[30 69 90]


In [32]:
from collections import Counter

# Define your array
my_array = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5]

# Use Counter to find the most common element
most_common = Counter(my_array).most_common(1)

if most_common:
    print("The most frequent value is:", most_common[0][0])
    print("It occurs", most_common[0][1], "times.")
else:
    print("The array is empty.")


The most frequent value is: 4
It occurs 4 times.


In [33]:
import numpy as np

# numerical array
my_array = np.array([12, 5, 9, 25, 7, 42, 8, 17])

# Specify the value of n 
n = 3

# Use NumPy to get the n largest values
n_largest_values = np.partition(my_array, -n)[-n:]

print(f"The {n} largest values are: {n_largest_values}")


The 3 largest values are: [17 42 25]


In [34]:
import numpy as np

# Create a regular array 
regular_array = [(1, 'Alice', 25),
                 (2, 'Bob', 30),
                 (3, 'Charlie', 35)]

# Define the field names for the record array
dtype = [('ID', int), ('Name', 'U10'), ('Age', int)]

# Create a record array from the regular array
record_array = np.array(regular_array, dtype=dtype)

# Access elements by field names
print("Record Array:")
print(record_array)

# Access specific fields
print("\nName column:")
print(record_array['Name'])

print("\nAge column:")
print(record_array['Age'])


Record Array:
[(1, 'Alice', 25) (2, 'Bob', 30) (3, 'Charlie', 35)]

Name column:
['Alice' 'Bob' 'Charlie']

Age column:
[25 30 35]


In [35]:
import numpy as np


my_array = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Specify the indices of the rows you want to swap 
row1_index = 0
row2_index = 2

# Swap the rows
my_array[[row1_index, row2_index]] = my_array[[row2_index, row1_index]]

print("Array after swapping rows:")
print(my_array)


Array after swapping rows:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [36]:
import numpy as np

# Create a 1D array
original_array = np.array([1, 2, 3, 4, 5, 6])


new_shape = (2, 3)  

# Reshape the original array
reshaped_array = original_array.reshape(new_shape)

print("Original Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)


Original Array:
[1 2 3 4 5 6]

Reshaped Array:
[[1 2 3]
 [4 5 6]]
